services:

  tuto_django_postgres:
    container_name: tuto_django_postgres
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=secret
      - POSTGRES_PORT=5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -d django
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  tuto_django_rabbitmq:
    container_name: tuto_django_rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_LOGS=-
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 3

  tuto_django:
    container_name: tuto_django
    build: .
    user: "1000:1000"
    command: make dev
    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      tuto_django_postgres:
        condition: service_healthy
      tuto_django_rabbitmq:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=tuto_django_postgres
      - POSTGRES_DB=project
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=secret
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=amqp://guest:guest@tuto_django_rabbitmq:5672//
      - CELERY_RESULT_BACKEND=django-db

  tuto_django_celery:
    container_name: tuto_django_celery
    build: .
    user: "1000:1000"
    command: poetry run celery -A project worker --loglevel=debug
    volumes:
      - .:/opt/app
    depends_on:
      tuto_django_rabbitmq:
        condition: service_healthy
      tuto_django_postgres:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@tuto_django_rabbitmq:5672//
      - CELERY_RESULT_BACKEND=django-db
      - POSTGRES_HOST=tuto_django_postgres
      - POSTGRES_DB=project
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=secret
      - POSTGRES_PORT=5432

  tuto_django_celery_beat:
    container_name: tuto_django_celery_beat
    build: .
    user: "1000:1000"
    command: poetry run celery -A project beat --loglevel=debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/opt/app
    depends_on:
      tuto_django_rabbitmq:
        condition: service_healthy
      tuto_django_postgres:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@tuto_django_rabbitmq:5672//
      - CELERY_RESULT_BACKEND=django-db
      - POSTGRES_HOST=tuto_django_postgres
      - POSTGRES_DB=project
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=secret
      - POSTGRES_PORT=5432

volumes:
  pg_data:
