version: '3.8'

services:

  tuto_django:
    container_name: tuto_django
    build:
      context: .
      dockerfile: ./Dockerfile
    user: "1000:1000"
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    tty: true
    volumes:
      - .:/opt/app
    restart: always
    environment:
      - DEBUG=False
      - DJANGO_SECRET_KEY=${SECRET_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=tuto
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PWD}
      - SITE_URL=${SITE_URL}
      - CELERY_BROKER_URL=amqp://guest:guest@tuto_django_rabbitmq:5672/
      - CELERY_RESULT_BACKEND=django-db
      - REDIS_URL=redis://tuto_django_redis:6379
    networks:
      internal:
      postgres:
    healthcheck:
      test: make health_check
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  tuto_django_celery:
    container_name: tuto_django_celery
    build: .
    user: "1000:1000"
    command: poetry run celery -A project worker --loglevel=debug
    volumes:
      - .:/opt/app
    depends_on:
      tuto_django_rabbitmq:
        condition: service_healthy
      tuto_django_postgres:
        condition: service_healthy
      tuto_django:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@tuto_django_rabbitmq:5672/
      - CELERY_RESULT_BACKEND=django-db
      - POSTGRES_HOST=tuto_django_postgres
      - POSTGRES_DB=project
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=secret
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://tuto_django_redis:6379
    networks:
      internal:
      postgres:
    healthcheck:
      test: celery -b amqp://guest:guest@tuto_django_rabbitmq:5672/ inspect ping
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  tuto_django_celery_beat:
    container_name: tuto_django_celery_beat
    build: .
    user: "1000:1000"
    command: poetry run celery -A project beat --loglevel=debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/opt/app
    depends_on:
      tuto_django_rabbitmq:
        condition: service_healthy
      tuto_django_postgres:
        condition: service_healthy
      tuto_django:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@tuto_django_rabbitmq:5672/
      - CELERY_RESULT_BACKEND=django-db
      - POSTGRES_HOST=tuto_django_postgres
      - POSTGRES_DB=project
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=secret
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://tuto_django_redis:6379
    networks:
      internal:
      postgres:
    healthcheck:
      test: celery -b amqp://guest:guest@tuto_django_rabbitmq:5672/ inspect ping
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    depends_on:
      - tuto_django
    image: nginx:stable
    volumes:
      - nginxlogs:/var/log/nginx
      - /path/to/static:/var/www/html/static
      - /path/to/media:/var/www/html/media
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/uwsgi_params:/etc/nginx/uwsgi_params:ro
    networks:
      - internal
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tuto-web.rule=Host(`my_hostname.fr`)"
      - "traefik.http.routers.tuto-web.entrypoints=web"
      - "traefik.http.routers.tuto-web.middlewares=traefik-redirect"
      - "traefik.http.routers.tuto-websecured.rule=Host(`my_hostname.fr`)"
      - "traefik.http.routers.tuto-websecured.entrypoints=websecure"
      - "traefik.http.routers.tuto-websecured.tls=true"
      - "traefik.http.routers.tuto-websecured.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.tuto-redirect.redirectscheme.scheme=https"

volumes:
  postgresdata:
  nginxlogs:

networks:
  external:
    name: external
    external: true
  internal:
  postgres:
